### ISSUE TITLE
Replace ntex AMQP codec

### ISSUE THREAD

**Issue by wolf4ood** [rabbitmq/rabbitmq-stream-rust-client#105]
Currently we the dependency `ntex-amqp-codec` for message serializaion/deserialization. But it for now is pinned to the version `0.7.2` since the next version contains breaking changes. We should find an alternative or create our own implementation of the AMQP message format

**Comment by Gsantomaggio** [comment]
Closed via https://github.com/rabbitmq/rabbitmq-stream-rust-client/pull/120
