### ISSUE TITLE
Smart Publisher Adapter

### ISSUE THREAD

**Issue by DavidSantacruzR** [rabbitmq/rabbitmq-stream-rust-client#154]
Hi, RabbitMQ team.

I'm working on a project, which is a wrapper/adapter to your library (great project!). So, to understand a bit more about it I'm trying to build a smart publisher but I have come across a problem related to publishing messages.

Here is my (noob) implementation of a smart publisher:

```rust
use rabbitmq_stream_client::{Environment, types::Message};

pub struct Publisher {
    data: String,
    event_queue: String
}

impl Publisher {
    pub fn new() -> PublisherBuilder {
        PublisherBuilder {
            data: None,
            event_queue: None
        }
    }
    pub async fn send_message(mut self) -> Result<(), Box<dyn std::error::Error>> {
        let event_queue = self.event_queue.as_str();
        let environment = Environment::builder().build().await?;
        let mut producer = environment.producer().name("test").build(event_queue).await?;
        producer
            .send(Message::builder().body(format!("{:?}", &self.data)).build(), ())
            .await?;
        producer.close().await?;
        Ok(println!("Sent message successfully with data: {:?}", &self.data?))
    }
}

#[derive(Debug)]
pub struct PublisherBuilder {
    data: Option<String>,
    event_queue: Option<String>,
}

impl PublisherBuilder {
    pub fn event_queue(mut self, event_queue: String) -> Self {
        self.event_queue = Some(event_queue);
        self
    }
    pub fn data(mut self, data: String) -> Self {
        self.data = Some(data);
        self
    }
    pub fn build(mut self) -> Publisher {
        Publisher {
            event_queue: self.event_queue?,
            data: self.data?
        }
    }
}

```

The thing is that I cannot publish any message, as I get getting an error related to a specific type as a second argument to the send function:

```rust
error[E0277]: expected a `Fn<(Result<rabbitmq_stream_client::producer::ConfirmationStatus, ProducerPublishError>,)>` closure, found `()`
   --> src/producer/mod.rs:20:81
    |
20  |             .send(Message::builder().body(format!("{:?}", &self.data)).build(), ())
    |              ---- required by a bound introduced by this call                   ^^ expected an `Fn<(Result<rabbitmq_stream_client::producer::ConfirmationStatus, ProducerPublishError>,)>` closure, found `()`
    |
    = help: the trait `Fn<(Result<rabbitmq_stream_client::producer::ConfirmationStatus, ProducerPublishError>,)>` is not implemented for `()`
note: required by a bound in `Producer::<Dedup>::send`
   --> /Users/davesaintcross/.cargo/registry/src/github.com-1ecc6299db9ec823/rabbitmq-stream-client-0.1.0/src/producer.rs:325:18
    |
325 |         cb: impl Fn(Result<ConfirmationStatus, ProducerPublishError>) -> Fut + Send + Sync + 'static,
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ required by this bound in `Producer::<Dedup>::send`
```

I really have no clue as to what to pass as a second argument, and I couldn't find any reference on your docs. I really appreciate any clarification on the issue.

By the way, the smart publisher is meant to be used this way:

```rust
let mut publisher = Publisher::new()
        .event_queue("loan_disbursed".to_string())
        .data("Some data".to_string())
        .build()
        .send();
```

**Comment by wolf4ood** [comment]
Hi @DavidSantacruzR 

thanks for raising this. 

If you want to use the `send` API you have to pass as second argument a callback for handling the confirmation status of the message, which arrives asynchronously from the server .

In your case it will be: 

```rust
   producer
            .send(Message::builder().body(format!("{:?}", &self.data)).build(), || async {})
            .await?;
```

But looking at your APIs probably you will need `send_with_confirm`, which just takes only the message.
This method will wait until the server confirm that the message has been published in the stream.

```rust
   producer
            .send_with_confirm(Message::builder().body(format!("{:?}", &self.data)).build())
            .await?;
```

Note that this will block until the confirm has been received, and it will be less performant compared to the `send` one if you use it for example in a for loop.

Let me know if this answer works for you :)

Meanwhile i will work on documenting better those APIs.

You can find some example [here](https://github.com/rabbitmq/rabbitmq-stream-rust-client/tree/main/examples)

Thanks

**Comment by DavidSantacruzR** [comment]
Hey! Thank you, great explanation as usual. I'll try both (send and with_confirm).

I really appreciate your response.

**Comment by DavidSantacruzR** [comment]
If you don't mind another question, Ive used the send_with_confirm, and effectively the message is sent, but the consumer doesn't consume the message so it stays in status: Ready.

The implementation of the consumer callback is the following. Is it possible to persist the consumer, so it's always listening to any incoming messages? Is this considered a bad practice?

```rust
impl Callback {
    pub fn new() -> CallbackBuilder {
        CallbackBuilder::default()
    }
    pub async fn handle(&mut self) -> Result<(), Box<dyn std::error::Error>>{
        let event_queue = self.event_queue.clone();
        let mut consumer = self.environment.consumer().build(event_queue.as_str()).await?;
        let handler = consumer.handle();
        task::spawn( async move {
            while let Some(delivery) = consumer.next().await {
                println!("Got message {:?}", delivery)
            }
        });
        // handler.close().await?;
        Ok(())
    }
}
```

Thank you for your response :).
![Screen Shot 2023-01-23 at 8 58 14 PM](https://user-images.githubusercontent.com/59373131/214197901-f7c1c932-46a6-48f3-8a5f-0b82aebe14b9.png)

**Comment by wolf4ood** [comment]
Hi @DavidSantacruzR  don't mind at all :)

I think you have to change the `OffsetSpecification` when building the consumer. By default is `OffestSpecification::Next`
which means that the client will start receiving only the messages once connected.

Here it's a blog post about offset

https://blog.rabbitmq.com/posts/2021/09/rabbitmq-streams-offset-tracking//

Let me know if this helps

Thanks

**Comment by DavidSantacruzR** [comment]
Sure thing, I'll experiment with it, and I'll post my findings here.

Thank you greatly for your response.

**Comment by DavidSantacruzR** [comment]
Hi @wolf4ood I tested doing changes on the ```OffsetSpecification``` and I'm still facing the same issue. So, I decided to checkout two of your code examples ``env_callbacks.rs```and ```batch_send.rs```, removing the code related to delete the stream.

``` rust
environment.delete_stream("test").await?;
```
And I can see that the consumer gets the messages but they don't get acknowledged.

Logger results:

![Screen Shot 2023-01-29 at 11 48 16 AM](https://user-images.githubusercontent.com/59373131/215342013-37717c3c-c0d6-448f-842b-e477f1773b0e.png)

RabbitMQ stream:

![Screen Shot 2023-01-29 at 11 48 06 AM](https://user-images.githubusercontent.com/59373131/215342019-cc6d323b-b856-4f48-ab9c-f926b3ba34cf.png)

**Comment by wolf4ood** [comment]
Hi @DavidSantacruzR 

what do you mean by the the messages don't get acknowledged. AFAIK that is a queue thing not in the stream.

In the stream there is a concept of offset store, but it's not yet implemented in the consumer.

**Comment by DavidSantacruzR** [comment]
Oh I see! Thank you for the clarification!
