### ISSUE TITLE
port Java API for environment / producer / consumer

### ISSUE THREAD

**Issue by 51yu** [rabbitmq/rabbitmq-stream-rust-client#158]
https://rabbitmq.github.io/rabbitmq-stream-java-client/snapshot/htmlsingle/#rabbitmq-stream-java-api

^^ several consumer / producer APIs are missing in Rust comparing to Java

**Comment by Gsantomaggio** [comment]
We are aware about that. We are working on it. Any contribution is welcome.

I will close the issue since we already have a schedule.
