### ISSUE TITLE
Docs for tls

### ISSUE THREAD

**Issue by DanielePalaia** [rabbitmq/rabbitmq-stream-rust-client#159]
Adding an example and updating the doc for the TLS support https://github.com/rabbitmq/rabbitmq-stream-rust-client/issues/94

**Comment by Gsantomaggio** [comment]
[Here](https://github.com/rabbitmq/rabbitmq-stream-rust-client/blob/main/examples/tls_producer.rs) the example 
[Readme TLS info](https://github.com/rabbitmq/rabbitmq-stream-rust-client#building-the-environment-with-tls)
