### ISSUE TITLE
None MessageResult, producer panic

### ISSUE THREAD

**Issue by 51yu** [rabbitmq/rabbitmq-stream-rust-client#162]
producer panic if message result is None ..
https://github.com/rabbitmq/rabbitmq-stream-rust-client/blob/main/src/producer.rs#L556

it happen few minutes after app run, and app exit with panic
how to handle it gracefully without app panic ?

**Comment by wolf4ood** [comment]
Hi @51yu 

thanks for raising this. So the basic  step to reproduce it is to setup a producer and after few minutes it should panic right?

**Comment by 51yu** [comment]
stacktrace

```
thread 'tokio-runtime-worker' panicked at 'not yet implemented', /rabbitmq-stream-client-0.1.0/src/producer.rs:558:21

<rabbitmq_stream_client::client::Client as rabbitmq_stream_client::client::handler::MessageHandler>::handle_message::{{closure}}::{{closure}}
             at rabbitmq-stream-client-0.1.0/src/client/mod.rs:100:81
```

**Comment by 51yu** [comment]
> Hi @51yu
> 
> thanks for raising this. So the basic step to reproduce it is to setup a producer and after few minutes it should panic right?

yes

**Comment by wolf4ood** [comment]
Hi @51yu 

I think the main issue is the heartbeat handling which is still missing, 
There where a PR in draft i can pick it from there and finish the work ASAP

Thanks

**Comment by 51yu** [comment]
Meanwhile, could we mitigate the issue by letting producer periodically publish dummy message to stream and let consumer ignore that ?

**Comment by wolf4ood** [comment]
The best workaround it would be to disable the heartbeat, but from client side it's is not exposed yet. I would wait for this fix, I think it could be available tomorrow :)
