### ISSUE TITLE
Consumer<Dedup>: publishing_id incorrect

### ISSUE THREAD

**Issue by medigor** [rabbitmq/rabbitmq-stream-rust-client#233]
### Describe the bug

Publishing_id calculated incorrectly.

### Reproduction steps

1. run next code 2 times:
```rust
let mut producer = environment
    .producer()
    .name("producer1")
    .build(stream)
    .await?;
        
for _ in 0..2 {
    producer
        .send(message.clone(), |result| async {
            let id = result.unwrap().publishing_id();
            println!("publishing_id: {id}");
        })
        .await?;
}
sleep(Duration::from_secs(1)).await;
```

first run result:
```sh
publishing_id: 9004087
publishing_id: 9004086
```
second run result:
```sh
publishing_id: 9004088
publishing_id: 9004087
```

### Expected behavior

Publishing_id  must be unique

### Additional context

Error in https://github.com/rabbitmq/rabbitmq-stream-rust-client/blob/main/src/producer.rs:
```rust
let publishing_id = match message.publishing_id() {
    Some(publishing_id) => *publishing_id,
    None => self.0.publish_sequence.fetch_add(1, Ordering::Relaxed),
};
```
`fetch_add` returning the previous value!

**Comment by wolf4ood** [comment]
Hi @medigor 

thanks for raising this, indeed there is an issue with the initialization of the query publisher sequence

let me work on a fix

**Comment by wolf4ood** [comment]
@medigor 

here's the [PR](https://github.com/rabbitmq/rabbitmq-stream-rust-client/pull/234)

**Comment by Gsantomaggio** [comment]
@medigor Can you please try it and confirm if it is working correctly? thank you

**Comment by medigor** [comment]
I have checked it, its working correctly. Thank you
