### ISSUE TITLE
Code coverage integration

### ISSUE THREAD

**Issue by wolf4ood** [rabbitmq/rabbitmq-stream-rust-client#37]
It would be nice to have an action for checking the coverage and publish the results on Codecov o Coveralls

**Comment by Gsantomaggio** [comment]
we ( @wolf4ood  ) 'd like to use codecov. 
@MirahImage ?

**Comment by MirahImage** [comment]
I think we need to add a license file, contributing guide, and code-of-conduct to properly make this project OSS (which we really need to add anyways), then it seems like we'd be fine by the codecov terms-of-service.

**Comment by Gsantomaggio** [comment]
Sure, we were thinking about  `MIT` licence

**Comment by Gsantomaggio** [comment]
closed via https://github.com/rabbitmq/rabbitmq-stream-rust-client/pull/112
