### ISSUE TITLE
Partitions [command]

### ISSUE THREAD

**Issue by korsmakolnikov** [rabbitmq/rabbitmq-stream-rust-client#8]
PartitionsQuery => Key Version CorrelationId SuperStream
  Key => uint16 // 25
  Version => uint16
  CorrelationId => uint32
  SuperStream => string

PartitionsResponse => Key Version CorrelationId [Stream]
  Key => uint16 // 25
  Version => uint16
  CorrelationId => uint32
  Stream => string

**Comment by Gsantomaggio** [comment]
part of https://github.com/rabbitmq/rabbitmq-stream-rust-client/issues/204
