### ISSUE TITLE
Docker Image

### ISSUE THREAD

**Issue by Gsantomaggio** [rabbitmq/rabbitmq-stream-rust-client#84]
Prepare a docker image to push in our pivotal docker hub to add clients in our LRE.

We already have perf-test in GO and Java, so I would avoid to create another perf test. 
The idea is to have a minimum set of commands to subscribe and publish messages.

 cc @gerhard

**Comment by MirahImage** [comment]
Does it make sense to test the Rust client in the LRE, given we're already testing streams 2 different ways in the LRE and the client itself is tested here in github actions?

**Comment by Gsantomaggio** [comment]
The idea is to have LRE also for the clients, to see if there are memory leaks, deadlocks etc. 
We found some issues in our clients in LRE.

I don't want to write another perf-test, just a minimal set of commands to run the client.

**Comment by Gsantomaggio** [comment]
Let's close it. At the moment the docker image is not needed.
