### ISSUE TITLE
Route [command]

### ISSUE THREAD

**Issue by korsmakolnikov** [rabbitmq/rabbitmq-stream-rust-client#9]
RouteQuery => Key Version CorrelationId RoutingKey SuperStream
  Key => uint16 // 24
  Version => uint16
  CorrelationId => uint32
  RoutingKey => string
  SuperStream => string

RouteResponse => Key Version CorrelationId Stream
  Key => uint16 // 24
  Version => uint16
  CorrelationId => uint32
  Stream => string

**Comment by Gsantomaggio** [comment]
part of https://github.com/rabbitmq/rabbitmq-stream-rust-client/issues/204
