### ISSUE TITLE
Add License and code-of-conduct 

### ISSUE THREAD

**Issue by Gsantomaggio** [rabbitmq/rabbitmq-stream-rust-client#91]
Add License and code-of-conduct

linked with https://github.com/rabbitmq/rabbitmq-stream-rust-client/issues/37#issuecomment-921765942

**Comment by MirahImage** [comment]
Assuming we were going to follow the same pattern as other clients, I added the MPL 2.0 and Apache 2.0 licenses. We could also triple license it, adding the MIT license as well if we want. I think we can also safely omit the MPL 2.0 if we want. I believe the Apache 2.0 license is important for some users, but open to discussion.

I also added the code of conduct, which is required for all VMware OSS projects.

**Comment by Gsantomaggio** [comment]
Ok no problem at all
